[workspace]
members = ["cargo:cli"]

[dist]
cargo-dist-version = "0.32.0"
ci = ["github"]
installers = []
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
]
unix-archive = ".tar.gz"
pr-run-mode = "plan"
allow-dirty = ["ci"]
